### ISSUE TITLE
是否可以提供静态编译文件。

### ISSUE THREAD

**Issue by ghostry** [lifenjoiner/pd#2]
看说明挺好的，是否能用来取代cow用到openwrtAMDX64上面。
比如把pd运行到主路由，转发到旁路由的socks5上面。
但是文档只有软件本身的配置。没有怎么用到系统里这部分。
是不是用iptables的 -j REDIRECT --to-ports 1081 这种命令转发到软件上面就行了？

**Comment by lifenjoiner** [comment]
已发布 v0.1.8，更新[用法示例](https://github.com/lifenjoiner/pd#%E7%94%A8%E6%B3%95)。

我不熟悉 openwrt，你自己试试。
