### ISSUE TITLE
Can you release the ARM?

### ISSUE THREAD

**Issue by ren-zzzzz** [lifenjoiner/pd#3]
- linux-armv6
- linux-armv7
- linux-armv8

**Comment by lifenjoiner** [comment]
You can cross compile it easily with [go](https://go.dev/dl/).

From Linux:
```sh
env GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="all=-s -w" -trimpath
```
From Windows:
```cmd
set GOOS=linux
set GOARCH=arm
set GOARM=6
go build -ldflags="all=-s -w" -trimpath
```

Supported `GOARCH` and `GOARM`:

Architecture | Status | GOARM value | GOARCH value
-- | -- | -- | --
ARMv4 and below | not supported | n/a | n/a
ARMv5 | supported | GOARM=5 | GOARCH=arm
ARMv6 | supported | GOARM=6 | GOARCH=arm
ARMv7 | supported | GOARM=7 | GOARCH=arm
ARMv8 | supported | n/a | GOARCH=arm64

Ref: https://go.dev/wiki/GoArm

**Comment by Ren-lh** [comment]
> 你可以用 [go](https://go.dev/dl/) 轻松交叉编译它。
> 
> 在 Linux 中：
> 
> ```shell
> env GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="all=-s -w" -trimpath
> ```
> 
> 在 Windows 中：
> 
> ```batchfile
> set GOOS=linux
> set GOARCH=arm
> set GOARM=6
> go build -ldflags="all=-s -w" -trimpath
> ```
> 
> 支持和：`GOARCH``GOARM`
> 
> 建筑	地位	GOARM价值	GOARCH价值观
> ARMv4 及以下版本	不支持	不适用	不适用
> ARMv5的	支持	GOARM=5	GOARCH=手臂
> ARMv6的	支持	GOARM=6	GOARCH=手臂
> ARMv7的	支持	GOARM=7	GOARCH=手臂
> ARMv8的	支持	不适用	GOARCH=arm64
> 编号： https://go.dev/wiki/GoArm

Thank you
