### ISSUE TITLE
从Cow过来的，请问下有什么方法可以把ss服务器挂载出不同的本地的127.0.0.1:xxxx地址方便pd调用？

### ISSUE THREAD

**Issue by youthcould** [lifenjoiner/pd#4]
一直觉得cow非常好用，可惜很多加密方式不支持了，由于pd不支持直连服务器，故请问下有什么方法可以把ss服务器挂载出不同的本地的127.0.0.1:xxxx地址方便pd调用？谢谢

**Comment by lifenjoiner** [comment]
当然是用服务者推荐的客户端啦。
```
{支持通用代理协议（HTTP/SOCKS）的程序} <===> {pd} <===> {专有协议的客户端} <=***=> {专有协议的服务端}
```

**Comment by youthcould** [comment]
谢谢回复，这个逻辑懂的，只是服务者提供的客户端也很难同时提供多个端口供pd调用吧？

**Comment by lifenjoiner** [comment]
pd 的上游当然也可以是一个，只要你能保证它足够稳定就可以了。
多个上游的目的在于，可以尝试不同协议或不同服务者的**多个实例**。每条线路的可用性都在波动，尽量选最好的。各个客户端有多条线路的话，又有自己的选优算法。两层选优，增加可用性。

**Comment by lifenjoiner** [comment]
想来，应该是你的客户端不支持修改监听端口。那只要它可靠，只一个也可以。
支持 ss 协议的客户端比较多，一般都是解压就可以用的，配置也很自由。这种，多复制一份，改一下监听端口，就能多一个实例。很多也支持同时监听多个端口，但是按照上面的逻辑，效果应该没有多实例好。
其它，不同的软件一般会监听不同的端口。

PS：你这长难句，又没介绍背景，咱们很难在同一出发点上……是我之前没有Get到你的关键问题在哪里

**Comment by youthcould** [comment]
收到，哈哈，非常抱歉。
