### ISSUE TITLE
大佬能不能把教程写得简单些?

### ISSUE THREAD

**Issue by linsan970809** [lifenjoiner/pd#5]
首先感谢大佬做的这个软件,但是教程我不太会用希望大佬能把教程写得简单些
我本地有一台独立的SOCK5代理服务器端口是10080,WIN10服务器IP:192.168.10.22
怎么写命令可以让PD运行起来?谢谢

另:如果大佬能编译一个WIN7版本也能用的,就更完美了,再次感谢

**Comment by lifenjoiner** [comment]
命令行嘛，首看帮助，总共也没有几个参数，按照说明设置就好，其次看`readme`，再者有例子的参考例子，自己多摸索尝试……
要先搞明白代理是什么、怎么运转的，这是隐含的预置要求，然后就能举一反三、自由组合。我不可能把每种可能都写出来。

我假设你是：
1. 有机器 A，对外提供代理 `socks5://192.168.10.22:10080`；
2. 想在机器 B 使用 A 的代理，并且 `pd`运行在 B。

那么，最简单的
```
pd -proxies=socks5://192.168.10.22:10080
```
B 上就有了一个只对本机服务的`127.0.0.1:6699`，接受 http 和 socks5 请求，但只有 socks5 协议有上游代理可用。
其它参数是默认，根据需要自己调整。

PS：
你最好多提供一个上游 http 代理，给浏览器之类的用。如`readme`里说的，`pd`只会"使用相同协议的上游代理原始请求"，即不做代理协议转换。

**Comment by linsan970809** [comment]
谢谢大佬,已经在B主机用了一段时间
pd -proxies=socks5://192.168.10.22:10080
发现一个问题,不知道是不是我遇到的个例,间隔一段时间这个B主机的代理就会变得不可用,大概4-5分钟后又会恢复正常.
A主机则一直都正常,我试过在B主机无法使用的时候直接切换到A主机的代理,上网就正常了,切换回来又不正常

**Comment by lifenjoiner** [comment]
让我猜谜玩儿吗？
日志、截图……详细的足够诊断问题的线索？

**Comment by linsan970809** [comment]
日志里其实看不太出来东西,我这两天有观察,它的这个中断没有预兆,也没有错误提示
比如这个日志,一中断我就去看了,划红线的地方是中断开始的时间,这个过程其实是中断了3分钟左右

可是回顾日志也有一定的连贯性,41分中断的,恢复时间应该是44分,但是日志里还是有42分的链接提示,就像程序暂停了3分钟,把这些请求都压住,然后再一次性释放出来,所以这个日志可以看到红线下面的时间排序是有错乱的不连贯

PS:中断的这个时间里我有尝试直接访问PD的2个上游代理,2个上游代理都是正常的

![20240326114623_o](https://github.com/lifenjoiner/pd/assets/61045370/b952cacb-5b62-4fb4-a3bc-8659a0d98a00)

**Comment by lifenjoiner** [comment]
1. 以后如果图不是更优，尽量提供文本，便于查找。图就只能肉眼看看。
2. “间隔一段时间这个B主机的代理就会变得不可用,大概4-5分钟后又会恢复正常”，是完全不能用了，还是只是其代理的某一个连接不通了？
3. 图中都是直连，没有走上游代理的，那么 B 通不通和 A 没有关系。
4. 你说的“压住”，我没有观察到过。看不出更多，信息不够找出问题。你这局域网用，客户端多吗，负载怎样，是在本地吗？
5. 换成 HTTP 代理试试，对比
