### ISSUE TITLE
试用了一下，感觉没有cow那么好用

### ISSUE THREAD

**Issue by midpoint** [lifenjoiner/pd#7]
试用了一下，感觉没有cow那么好用

**Comment by lifenjoiner** [comment]
没有……，全是感情。不过，是消极的。Frankly, 少提，并不能解决什么问题，只是自己一时爽。
没有人愿意分享了自己的劳动成果之后，还要当别人的情绪垃圾桶。不少开源者都是这样败兴而放弃的。

**Comment by DrayChou** [comment]
挺好的，适合整合一堆乱七八糟的代理。
感谢作者
