### ISSUE TITLE
运行窗口能隐藏起来吗？

### ISSUE THREAD

**Issue by midpoint** [lifenjoiner/pd#9]
任务栏一直有个运行窗口，如果能隐藏到右下角就好了

**Comment by lifenjoiner** [comment]
搭配个其它程序就好啦。简单的很！搜一下嘛~

推荐：
1. https://github.com/plastovicka/HotkeyP
2. https://github.com/fcFn/traymond

其它参考：[A software that puts any application to the system tray](https://www.reddit.com/r/software/comments/mskgvn/a_software_that_puts_any_application_to_the/)
